version: '3.8'
services:
  frontend-app:
    image: ghcr.io/adrianeka/glucoseclamp-frontend:latest # Menggunakan image dari GHCR
    container_name: glucoseclamp-frontend
    ports:
      - "3000:3000"
    networks:
      - glucose-network
    restart: always

networks:
  glucose-network:
    external: true